application-05:
  visibility: public
  repository_owner: cx-soral
  repository_name: application-05
  template_owner: cx-soral
  template_name: gcp-application
gcp-framework:
  visibility: public
  repository_owner: cx-soral
  repository_name: gcp-framework
  template_owner: cx-soral
  template_name: gcp-template-python
gcp-template-module:
  visibility: public
  is_template: true
  repository_owner: cx-soral
  repository_name: gcp-template-module
  template_owner: cx-soral
  template_name: gcp-template-python
