settings:
  realm_name: soral-base
  realm_project: soral-base
  realm_region: eu
  billing_account: 010054-67434E-D5BFF4
  foundation_name: soral-app
  project_prefix: soral-app-
  project_region: europe-west1
environments:
  dev:
    match_branch: refs/heads/main
    review_users:
      - cx-soral
  sit:
    match_branch: refs/tags/.*
  prd:
    match_branch: refs/tags/.*
modules:
  gcp_module_table:
    applications:
      - application-05
  gcp_module_dataset:
    applications:
      - application-05
  gcp_module_pypi_gcp:
    applications:
      - gcp-framework
