settings:
  realm_name: soral-base
  realm_project: soral-base
  billing_account: 010054-67434E-D5BFF4
  foundation_name: soral-app
  project_prefix: soral-app-
environments:
  dev:
    branch: main
  sit:
    branch: tags
  prd:
    branch: null
