settings:
  realm_name: soral-base
  realm_project: soral-base
  realm_region: eu
  billing_account: 010054-67434E-D5BFF4
  foundation_name: soral-app
  project_prefix: soral-app-
environments:
  dev:
    match_branch: refs/heads/main
  sit:
    match_branch: refs/tags/.*
  prd:
    match_branch: refs/tags/.*
modules:
  gcp_module_table:
    applications:
      - application-05
  gcp_module_dataset:
    applications:
      - application-05
  gcp_module_pypi_gcp:
    repository_region: europe-west1
    applications:
      - gcp-framework
      - gcp-template-module
