settings:
  realm_name: soral-base
  realm_project: soral-base
  foundation_name: null
  project_prefix: soral-app-
environments:
  dev:
    branch: main
  sit:
    branch: tags
  prd:
    branch: null
