settings:
  realm_name: soral-base
  realm_project: soral-base
  realm_region: eu
  billing_account: 010054-67434E-D5BFF4
  foundation_name: soral-app
  project_prefix: soral-app-
environments:
  dev:
    match_branch: refs/heads/main
  sit:
    match_branch: refs/tags/.*
  prd:
    match_branch: none^
modules:
  gcp_module_table:
    package: gcp-module-bigquery
    class: Table
    applications:
      - application-05
