gcp_module_project:
  events:
    - deploy
gcp_module_application:
  events:
    - deploy
gcp_module_pypi_gcp:
  events:
    - activate
gcp_module_table:
  events:
    - activate
gcp_module_dataset:
  events:
    - activate
